[css-size-adjust] Add "Ignored terms: text-wrap" to fix bikeshed fatal error.
The error I'm fixing is:
  FATAL ERROR: The only 'property' refs for 'text-wrap' were in ignored specs:
which is happening because css-text-4 is an ignored spec.  Since there
doesn't seem to be a way to remove things from the set of ignored specs,
I'll instead add to ignored terms.