Stop using <style scoped> to fix fatal bikeshed error.
The error fixed was:
FATAL ERROR: <style scoped> is no longer part of HTML. Ensure your styles can apply document-globally and remove the scoped attribute.

In this case, the styles were already written to apply globally, so they
only needed to be moved.